version: '3'

services: 

  nats-server:
    image: nats:latest
    ports:
      - 8222:8222

  # ============================ #
  # Client gateway microservices #
  # ============================ #

  client-gateway:
    build: 
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/store-microservices-course/image-registry/client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222

  # ================== #
  # Auth microservices #
  # ================== #
  auth-ms:
    build: 
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/store-microservices-course/image-registry/auth-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: southamerica-west1-docker.pkg.dev/store-microservices-course/image-registry/products-ms
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args: 
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: southamerica-west1-docker.pkg.dev/store-microservices-course/image-registry/orders-ms
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222


  # ====================== #
  # Payments microservices #
  # ====================== #
  payments-ms:
    build: 
      context: ./payments-ms
      dockerfile: dockerfile.prod
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    image: southamerica-west1-docker.pkg.dev/store-microservices-course/image-registry/payments-ms
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - PAYMENTS_PORT=${PAYMENTS_PORT}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET_HOOKDECK=${ENDPOINT_SECRET_HOOKDECK}
  
