apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/store-microservices-course/image-registry/orders-ms
        name: orders-ms
        env:
        - name: PORT
          value: "3002"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef: 
              name: 'orders-secrets'
              key: 'database_url'

        resources: {}
status: {}
